INSERT INTO students (group_code, surname, gender) VALUES (1, 'Einstein', 'm');
INSERT INTO students (group_code, surname, gender) VALUES (1, 'Newton', 'm');
INSERT INTO students (group_code, surname, gender) VALUES (1, 'Curie', 'f');
INSERT INTO students (group_code, surname, gender) VALUES (2, 'Tesla', 'm');
INSERT INTO students (group_code, surname, gender) VALUES (2, 'Wenjun', 'f');
INSERT INTO students (group_code, surname, gender) VALUES (2, 'Chivchyan', 'm');
INSERT INTO students (group_code, surname, gender) VALUES (1, 'Einstein', 'm');
INSERT INTO students (group_code, surname, gender) VALUES (1, 'Newton', 'm');
INSERT INTO students (group_code, surname, gender) VALUES (1, 'Curie', 'f');
INSERT INTO students (group_code, surname, gender) VALUES (2, 'Tesla', 'm');
INSERT INTO students (group_code, surname, gender) VALUES (2, 'Wenjun', 'f');
INSERT INTO students (group_code, surname, gender) VALUES (2, 'Chivchyan', 'm');
INSERT INTO students (group_code, surname, gender) VALUES (1, 'Einstein', 'm');
INSERT INTO students (group_code, surname, gender) VALUES (1, 'Newton', 'm');
INSERT INTO students (group_code, surname, gender) VALUES (1, 'Curie', 'f');
INSERT INTO students (group_code, surname, gender) VALUES (2, 'Tesla', 'm');
INSERT INTO students (group_code, surname, gender) VALUES (2, 'Wenjun', 'f');
INSERT INTO students (group_code, surname, gender) VALUES (2, 'Chivchyan', 'm');
INSERT INTO students (group_code, surname, gender) VALUES (1, 'Einstein', 'm');
INSERT INTO students (group_code, surname, gender) VALUES (1, 'Newton', 'm');
INSERT INTO students (group_code, surname, gender) VALUES (1, 'Curie', 'f');
INSERT INTO students (group_code, surname, gender) VALUES (2, 'Tesla', 'm');
INSERT INTO students (group_code, surname, gender) VALUES (2, 'Wenjun', 'f');
INSERT INTO students (group_code, surname, gender) VALUES (2, 'Chivchyan', 'm');
INSERT INTO students (group_code, surname, gender) VALUES (1, 'Einstein', 'm');
INSERT INTO students (group_code, surname, gender) VALUES (1, 'Newton', 'm');
INSERT INTO students (group_code, surname, gender) VALUES (1, 'Curie', 'f');
INSERT INTO students (group_code, surname, gender) VALUES (2, 'Tesla', 'm');
INSERT INTO students (group_code, surname, gender) VALUES (2, 'Wenjun', 'f');
INSERT INTO students (group_code, surname, gender) VALUES (2, 'Chivchyan', 'm');
INSERT INTO students (group_code, surname, gender) VALUES (1, 'Einstein', 'm');
INSERT INTO students (group_code, surname, gender) VALUES (1, 'Newton', 'm');
INSERT INTO students (group_code, surname, gender) VALUES (1, 'Curie', 'f');
INSERT INTO students (group_code, surname, gender) VALUES (2, 'Tesla', 'm');
INSERT INTO students (group_code, surname, gender) VALUES (2, 'Wenjun', 'f');
INSERT INTO students (group_code, surname, gender) VALUES (2, 'Chivchyan', 'm');
INSERT INTO students (group_code, surname, gender) VALUES (1, 'Einstein', 'm');
INSERT INTO students (group_code, surname, gender) VALUES (1, 'Newton', 'm');
INSERT INTO students (group_code, surname, gender) VALUES (1, 'Curie', 'f');
INSERT INTO students (group_code, surname, gender) VALUES (2, 'Tesla', 'm');
INSERT INTO students (group_code, surname, gender) VALUES (2, 'Wenjun', 'f');
INSERT INTO students (group_code, surname, gender) VALUES (2, 'Chivchyan', 'm');
INSERT INTO students (group_code, surname, gender) VALUES (1, 'Einstein', 'm');
INSERT INTO students (group_code, surname, gender) VALUES (1, 'Newton', 'm');
INSERT INTO students (group_code, surname, gender) VALUES (1, 'Curie', 'f');
INSERT INTO students (group_code, surname, gender) VALUES (2, 'Tesla', 'm');
INSERT INTO students (group_code, surname, gender) VALUES (2, 'Wenjun', 'f');
INSERT INTO students (group_code, surname, gender) VALUES (2, 'Chivchyan', 'm');
INSERT INTO students (group_code, surname, gender) VALUES (1, 'Einstein', 'm');
INSERT INTO students (group_code, surname, gender) VALUES (1, 'Newton', 'm');
INSERT INTO students (group_code, surname, gender) VALUES (1, 'Curie', 'f');
INSERT INTO students (group_code, surname, gender) VALUES (2, 'Tesla', 'm');
INSERT INTO students (group_code, surname, gender) VALUES (2, 'Wenjun', 'f');
INSERT INTO students (group_code, surname, gender) VALUES (2, 'Chivchyan', 'm');
INSERT INTO students (group_code, surname, gender) VALUES (1, 'Einstein', 'm');
INSERT INTO students (group_code, surname, gender) VALUES (1, 'Newton', 'm');
INSERT INTO students (group_code, surname, gender) VALUES (1, 'Curie', 'f');
INSERT INTO students (group_code, surname, gender) VALUES (2, 'Tesla', 'm');
INSERT INTO students (group_code, surname, gender) VALUES (2, 'Wenjun', 'f');
INSERT INTO students (group_code, surname, gender) VALUES (2, 'Chivchyan', 'm');
INSERT INTO students (group_code, surname, gender) VALUES (1, 'Einstein', 'm');
INSERT INTO students (group_code, surname, gender) VALUES (1, 'Newton', 'm');
INSERT INTO students (group_code, surname, gender) VALUES (1, 'Curie', 'f');
INSERT INTO students (group_code, surname, gender) VALUES (2, 'Tesla', 'm');
INSERT INTO students (group_code, surname, gender) VALUES (2, 'Wenjun', 'f');
INSERT INTO students (group_code, surname, gender) VALUES (2, 'Chivchyan', 'm');
INSERT INTO students (group_code, surname, gender) VALUES (1, 'Einstein', 'm');
INSERT INTO students (group_code, surname, gender) VALUES (1, 'Newton', 'm');
INSERT INTO students (group_code, surname, gender) VALUES (1, 'Curie', 'f');
INSERT INTO students (group_code, surname, gender) VALUES (2, 'Tesla', 'm');
INSERT INTO students (group_code, surname, gender) VALUES (2, 'Wenjun', 'f');
INSERT INTO students (group_code, surname, gender) VALUES (2, 'Chivchyan', 'm');
INSERT INTO students (group_code, surname, gender) VALUES (1, 'Einstein', 'm');
INSERT INTO students (group_code, surname, gender) VALUES (1, 'Newton', 'm');
INSERT INTO students (group_code, surname, gender) VALUES (1, 'Curie', 'f');
INSERT INTO students (group_code, surname, gender) VALUES (2, 'Tesla', 'm');
INSERT INTO students (group_code, surname, gender) VALUES (2, 'Wenjun', 'f');
INSERT INTO students (group_code, surname, gender) VALUES (2, 'Chivchyan', 'm');
INSERT INTO students (group_code, surname, gender) VALUES (1, 'Einstein', 'm');
INSERT INTO students (group_code, surname, gender) VALUES (1, 'Newton', 'm');
INSERT INTO students (group_code, surname, gender) VALUES (1, 'Curie', 'f');
INSERT INTO students (group_code, surname, gender) VALUES (2, 'Tesla', 'm');
INSERT INTO students (group_code, surname, gender) VALUES (2, 'Wenjun', 'f');
INSERT INTO students (group_code, surname, gender) VALUES (2, 'Chivchyan', 'm');
INSERT INTO students (group_code, surname, gender) VALUES (1, 'Einstein', 'm');
INSERT INTO students (group_code, surname, gender) VALUES (1, 'Newton', 'm');
INSERT INTO students (group_code, surname, gender) VALUES (1, 'Curie', 'f');
INSERT INTO students (group_code, surname, gender) VALUES (2, 'Tesla', 'm');
INSERT INTO students (group_code, surname, gender) VALUES (2, 'Wenjun', 'f');
INSERT INTO students (group_code, surname, gender) VALUES (2, 'Chivchyan', 'm');
INSERT INTO students (group_code, surname, gender) VALUES (1, 'Einstein', 'm');
INSERT INTO students (group_code, surname, gender) VALUES (1, 'Newton', 'm');
INSERT INTO students (group_code, surname, gender) VALUES (1, 'Curie', 'f');
INSERT INTO students (group_code, surname, gender) VALUES (2, 'Tesla', 'm');
INSERT INTO students (group_code, surname, gender) VALUES (2, 'Wenjun', 'f');
INSERT INTO students (group_code, surname, gender) VALUES (2, 'Chivchyan', 'm');
INSERT INTO students (group_code, surname, gender) VALUES (1, 'Einstein', 'm');
INSERT INTO students (group_code, surname, gender) VALUES (1, 'Newton', 'm');
INSERT INTO students (group_code, surname, gender) VALUES (1, 'Curie', 'f');
INSERT INTO students (group_code, surname, gender) VALUES (2, 'Tesla', 'm');
INSERT INTO students (group_code, surname, gender) VALUES (2, 'Wenjun', 'f');
INSERT INTO students (group_code, surname, gender) VALUES (2, 'Chivchyan', 'm');
INSERT INTO students (group_code, surname, gender) VALUES (1, 'Einstein', 'm');
INSERT INTO students (group_code, surname, gender) VALUES (1, 'Newton', 'm');
INSERT INTO students (group_code, surname, gender) VALUES (1, 'Curie', 'f');
INSERT INTO students (group_code, surname, gender) VALUES (2, 'Tesla', 'm');
INSERT INTO students (group_code, surname, gender) VALUES (2, 'Wenjun', 'f');
INSERT INTO students (group_code, surname, gender) VALUES (2, 'Chivchyan', 'm');
INSERT INTO students (group_code, surname, gender) VALUES (1, 'Einstein', 'm');
INSERT INTO students (group_code, surname, gender) VALUES (1, 'Newton', 'm');
INSERT INTO students (group_code, surname, gender) VALUES (1, 'Curie', 'f');
INSERT INTO students (group_code, surname, gender) VALUES (2, 'Tesla', 'm');
INSERT INTO students (group_code, surname, gender) VALUES (2, 'Wenjun', 'f');
INSERT INTO students (group_code, surname, gender) VALUES (2, 'Chivchyan', 'm');
INSERT INTO students (group_code, surname, gender) VALUES (1, 'Einstein', 'm');
INSERT INTO students (group_code, surname, gender) VALUES (1, 'Newton', 'm');
INSERT INTO students (group_code, surname, gender) VALUES (1, 'Curie', 'f');
INSERT INTO students (group_code, surname, gender) VALUES (2, 'Tesla', 'm');
INSERT INTO students (group_code, surname, gender) VALUES (2, 'Wenjun', 'f');
INSERT INTO students (group_code, surname, gender) VALUES (2, 'Chivchyan', 'm');
INSERT INTO students (group_code, surname, gender) VALUES (1, 'Einstein', 'm');
INSERT INTO students (group_code, surname, gender) VALUES (1, 'Newton', 'm');
INSERT INTO students (group_code, surname, gender) VALUES (1, 'Curie', 'f');
INSERT INTO students (group_code, surname, gender) VALUES (2, 'Tesla', 'm');
INSERT INTO students (group_code, surname, gender) VALUES (2, 'Wenjun', 'f');
INSERT INTO students (group_code, surname, gender) VALUES (2, 'Chivchyan', 'm');
INSERT INTO students (group_code, surname, gender) VALUES (1, 'Einstein', 'm');
INSERT INTO students (group_code, surname, gender) VALUES (1, 'Newton', 'm');
INSERT INTO students (group_code, surname, gender) VALUES (1, 'Curie', 'f');
INSERT INTO students (group_code, surname, gender) VALUES (2, 'Tesla', 'm');
INSERT INTO students (group_code, surname, gender) VALUES (2, 'Wenjun', 'f');
INSERT INTO students (group_code, surname, gender) VALUES (2, 'Chivchyan', 'm');
INSERT INTO students (group_code, surname, gender) VALUES (1, 'Einstein', 'm');
INSERT INTO students (group_code, surname, gender) VALUES (1, 'Newton', 'm');
INSERT INTO students (group_code, surname, gender) VALUES (1, 'Curie', 'f');
INSERT INTO students (group_code, surname, gender) VALUES (2, 'Tesla', 'm');
INSERT INTO students (group_code, surname, gender) VALUES (2, 'Wenjun', 'f');
INSERT INTO students (group_code, surname, gender) VALUES (2, 'Chivchyan', 'm');
INSERT INTO students (group_code, surname, gender) VALUES (1, 'Einstein', 'm');
INSERT INTO students (group_code, surname, gender) VALUES (1, 'Newton', 'm');
INSERT INTO students (group_code, surname, gender) VALUES (1, 'Curie', 'f');
INSERT INTO students (group_code, surname, gender) VALUES (2, 'Tesla', 'm');
INSERT INTO students (group_code, surname, gender) VALUES (2, 'Wenjun', 'f');
INSERT INTO students (group_code, surname, gender) VALUES (2, 'Chivchyan', 'm');
INSERT INTO students (group_code, surname, gender) VALUES (1, 'Einstein', 'm');
INSERT INTO students (group_code, surname, gender) VALUES (1, 'Newton', 'm');
INSERT INTO students (group_code, surname, gender) VALUES (1, 'Curie', 'f');
INSERT INTO students (group_code, surname, gender) VALUES (2, 'Tesla', 'm');
INSERT INTO students (group_code, surname, gender) VALUES (2, 'Wenjun', 'f');
INSERT INTO students (group_code, surname, gender) VALUES (2, 'Chivchyan', 'm');
INSERT INTO students (group_code, surname, gender) VALUES (1, 'Einstein', 'm');
INSERT INTO students (group_code, surname, gender) VALUES (1, 'Newton', 'm');
INSERT INTO students (group_code, surname, gender) VALUES (1, 'Curie', 'f');
INSERT INTO students (group_code, surname, gender) VALUES (2, 'Tesla', 'm');
INSERT INTO students (group_code, surname, gender) VALUES (2, 'Wenjun', 'f');
INSERT INTO students (group_code, surname, gender) VALUES (2, 'Chivchyan', 'm');
INSERT INTO students (group_code, surname, gender) VALUES (1, 'Einstein', 'm');
INSERT INTO students (group_code, surname, gender) VALUES (1, 'Newton', 'm');
INSERT INTO students (group_code, surname, gender) VALUES (1, 'Curie', 'f');
INSERT INTO students (group_code, surname, gender) VALUES (2, 'Tesla', 'm');
INSERT INTO students (group_code, surname, gender) VALUES (2, 'Wenjun', 'f');
INSERT INTO students (group_code, surname, gender) VALUES (2, 'Chivchyan', 'm');
INSERT INTO students (group_code, surname, gender) VALUES (1, 'Einstein', 'm');
INSERT INTO students (group_code, surname, gender) VALUES (1, 'Newton', 'm');
INSERT INTO students (group_code, surname, gender) VALUES (1, 'Curie', 'f');
INSERT INTO students (group_code, surname, gender) VALUES (2, 'Tesla', 'm');
INSERT INTO students (group_code, surname, gender) VALUES (2, 'Wenjun', 'f');
INSERT INTO students (group_code, surname, gender) VALUES (2, 'Chivchyan', 'm');
INSERT INTO students (group_code, surname, gender) VALUES (1, 'Einstein', 'm');
INSERT INTO students (group_code, surname, gender) VALUES (1, 'Newton', 'm');
INSERT INTO students (group_code, surname, gender) VALUES (1, 'Curie', 'f');
INSERT INTO students (group_code, surname, gender) VALUES (2, 'Tesla', 'm');
INSERT INTO students (group_code, surname, gender) VALUES (2, 'Wenjun', 'f');
INSERT INTO students (group_code, surname, gender) VALUES (2, 'Chivchyan', 'm');
INSERT INTO students (group_code, surname, gender) VALUES (1, 'Einstein', 'm');
INSERT INTO students (group_code, surname, gender) VALUES (1, 'Newton', 'm');
INSERT INTO students (group_code, surname, gender) VALUES (1, 'Curie', 'f');
INSERT INTO students (group_code, surname, gender) VALUES (2, 'Tesla', 'm');
INSERT INTO students (group_code, surname, gender) VALUES (2, 'Wenjun', 'f');
INSERT INTO students (group_code, surname, gender) VALUES (2, 'Chivchyan', 'm');
INSERT INTO students (group_code, surname, gender) VALUES (1, 'Einstein', 'm');
INSERT INTO students (group_code, surname, gender) VALUES (1, 'Newton', 'm');
INSERT INTO students (group_code, surname, gender) VALUES (1, 'Curie', 'f');
INSERT INTO students (group_code, surname, gender) VALUES (2, 'Tesla', 'm');
INSERT INTO students (group_code, surname, gender) VALUES (2, 'Wenjun', 'f');
INSERT INTO students (group_code, surname, gender) VALUES (2, 'Chivchyan', 'm');
INSERT INTO students (group_code, surname, gender) VALUES (1, 'Einstein', 'm');
INSERT INTO students (group_code, surname, gender) VALUES (1, 'Newton', 'm');
INSERT INTO students (group_code, surname, gender) VALUES (1, 'Curie', 'f');
INSERT INTO students (group_code, surname, gender) VALUES (2, 'Tesla', 'm');
INSERT INTO students (group_code, surname, gender) VALUES (2, 'Wenjun', 'f');
INSERT INTO students (group_code, surname, gender) VALUES (2, 'Chivchyan', 'm');








INSERT INTO exams (discipline_code, group_code, student_id, grade) VALUES (1, 1, 1, 5);
INSERT INTO exams (discipline_code, group_code, student_id, grade) VALUES (2, 1, 1, 5);
INSERT INTO exams (discipline_code, group_code, student_id, grade) VALUES (1, 1, 2, 5);
INSERT INTO exams (discipline_code, group_code, student_id, grade) VALUES (2, 1, 2, 5);
INSERT INTO exams (discipline_code, group_code, student_id, grade) VALUES (1, 1, 3, 5);
INSERT INTO exams (discipline_code, group_code, student_id, grade) VALUES (2, 1, 3, 5);
INSERT INTO exams (discipline_code, group_code, student_id, grade) VALUES (1, 1, 4, 5);
INSERT INTO exams (discipline_code, group_code, student_id, grade) VALUES (2, 1, 4, 5);
INSERT INTO exams (discipline_code, group_code, student_id, grade) VALUES (1, 1, 5, 5);
INSERT INTO exams (discipline_code, group_code, student_id, grade) VALUES (2, 1, 5, 5);
INSERT INTO exams (discipline_code, group_code, student_id, grade) VALUES (1, 1, 6, 5);
INSERT INTO exams (discipline_code, group_code, student_id, grade) VALUES (2, 1, 6, 5);
INSERT INTO exams (discipline_code, group_code, student_id, grade) VALUES (1, 1, 7, 5);
INSERT INTO exams (discipline_code, group_code, student_id, grade) VALUES (2, 1, 7, 5);
INSERT INTO exams (discipline_code, group_code, student_id, grade) VALUES (1, 1, 8, 5);
INSERT INTO exams (discipline_code, group_code, student_id, grade) VALUES (2, 1, 8, 5);
INSERT INTO exams (discipline_code, group_code, student_id, grade) VALUES (1, 1, 9, 5);
INSERT INTO exams (discipline_code, group_code, student_id, grade) VALUES (2, 1, 9, 5);
INSERT INTO exams (discipline_code, group_code, student_id, grade) VALUES (1, 1, 10, 5);
INSERT INTO exams (discipline_code, group_code, student_id, grade) VALUES (2, 1, 10, 5);
INSERT INTO exams (discipline_code, group_code, student_id, grade) VALUES (1, 1, 11, 5);
INSERT INTO exams (discipline_code, group_code, student_id, grade) VALUES (2, 1, 11, 5);
INSERT INTO exams (discipline_code, group_code, student_id, grade) VALUES (1, 1, 12, 5);
INSERT INTO exams (discipline_code, group_code, student_id, grade) VALUES (2, 1, 12, 5);
INSERT INTO exams (discipline_code, group_code, student_id, grade) VALUES (1, 1, 13, 5);
INSERT INTO exams (discipline_code, group_code, student_id, grade) VALUES (2, 1, 13, 5);
INSERT INTO exams (discipline_code, group_code, student_id, grade) VALUES (1, 1, 14, 5);
INSERT INTO exams (discipline_code, group_code, student_id, grade) VALUES (2, 1, 14, 5);
INSERT INTO exams (discipline_code, group_code, student_id, grade) VALUES (1, 1, 15, 5);
INSERT INTO exams (discipline_code, group_code, student_id, grade) VALUES (2, 1, 15, 5);
INSERT INTO exams (discipline_code, group_code, student_id, grade) VALUES (1, 1, 16, 5);
INSERT INTO exams (discipline_code, group_code, student_id, grade) VALUES (2, 1, 16, 5);
INSERT INTO exams (discipline_code, group_code, student_id, grade) VALUES (1, 1, 17, 5);
INSERT INTO exams (discipline_code, group_code, student_id, grade) VALUES (2, 1, 17, 5);
INSERT INTO exams (discipline_code, group_code, student_id, grade) VALUES (1, 1, 18, 5);
INSERT INTO exams (discipline_code, group_code, student_id, grade) VALUES (2, 1, 18, 5);
INSERT INTO exams (discipline_code, group_code, student_id, grade) VALUES (1, 1, 19, 5);
INSERT INTO exams (discipline_code, group_code, student_id, grade) VALUES (2, 1, 19, 5);
INSERT INTO exams (discipline_code, group_code, student_id, grade) VALUES (1, 1, 20, 5);
INSERT INTO exams (discipline_code, group_code, student_id, grade) VALUES (2, 1, 20, 5);
INSERT INTO exams (discipline_code, group_code, student_id, grade) VALUES (1, 1, 21, 5);
INSERT INTO exams (discipline_code, group_code, student_id, grade) VALUES (2, 1, 21, 5);
INSERT INTO exams (discipline_code, group_code, student_id, grade) VALUES (1, 1, 22, 5);
INSERT INTO exams (discipline_code, group_code, student_id, grade) VALUES (2, 1, 22, 5);
INSERT INTO exams (discipline_code, group_code, student_id, grade) VALUES (1, 1, 23, 5);
INSERT INTO exams (discipline_code, group_code, student_id, grade) VALUES (2, 1, 23, 5);
INSERT INTO exams (discipline_code, group_code, student_id, grade) VALUES (1, 1, 24, 5);
INSERT INTO exams (discipline_code, group_code, student_id, grade) VALUES (2, 1, 24, 5);
INSERT INTO exams (discipline_code, group_code, student_id, grade) VALUES (1, 1, 25, 5);
INSERT INTO exams (discipline_code, group_code, student_id, grade) VALUES (2, 1, 25, 5);
INSERT INTO exams (discipline_code, group_code, student_id, grade) VALUES (1, 1, 26, 5);
INSERT INTO exams (discipline_code, group_code, student_id, grade) VALUES (2, 1, 26, 5);
INSERT INTO exams (discipline_code, group_code, student_id, grade) VALUES (1, 1, 27, 5);
INSERT INTO exams (discipline_code, group_code, student_id, grade) VALUES (2, 1, 27, 5);
INSERT INTO exams (discipline_code, group_code, student_id, grade) VALUES (1, 1, 28, 5);
INSERT INTO exams (discipline_code, group_code, student_id, grade) VALUES (2, 1, 28, 5);
INSERT INTO exams (discipline_code, group_code, student_id, grade) VALUES (1, 1, 29, 5);
INSERT INTO exams (discipline_code, group_code, student_id, grade) VALUES (2, 1, 29, 5);
INSERT INTO exams (discipline_code, group_code, student_id, grade) VALUES (1, 1, 30, 5);
INSERT INTO exams (discipline_code, group_code, student_id, grade) VALUES (2, 1, 30, 5);
INSERT INTO exams (discipline_code, group_code, student_id, grade) VALUES (1, 1, 31, 5);
INSERT INTO exams (discipline_code, group_code, student_id, grade) VALUES (2, 1, 31, 5);
INSERT INTO exams (discipline_code, group_code, student_id, grade) VALUES (1, 1, 32, 5);
INSERT INTO exams (discipline_code, group_code, student_id, grade) VALUES (2, 1, 32, 5);

INSERT INTO exams (discipline_code, group_code, student_id, grade) VALUES (1, 2, 1, 5);
INSERT INTO exams (discipline_code, group_code, student_id, grade) VALUES (2, 2, 1, 5);
INSERT INTO exams (discipline_code, group_code, student_id, grade) VALUES (1, 2, 2, 5);
INSERT INTO exams (discipline_code, group_code, student_id, grade) VALUES (2, 2, 2, 5);
INSERT INTO exams (discipline_code, group_code, student_id, grade) VALUES (1, 2, 3, 5);
INSERT INTO exams (discipline_code, group_code, student_id, grade) VALUES (2, 2, 3, 5);
INSERT INTO exams (discipline_code, group_code, student_id, grade) VALUES (1, 2, 4, 5);
INSERT INTO exams (discipline_code, group_code, student_id, grade) VALUES (2, 2, 4, 5);
INSERT INTO exams (discipline_code, group_code, student_id, grade) VALUES (1, 2, 5, 5);
INSERT INTO exams (discipline_code, group_code, student_id, grade) VALUES (2, 2, 5, 5);
INSERT INTO exams (discipline_code, group_code, student_id, grade) VALUES (1, 2, 6, 5);
INSERT INTO exams (discipline_code, group_code, student_id, grade) VALUES (2, 2, 6, 5);
INSERT INTO exams (discipline_code, group_code, student_id, grade) VALUES (1, 2, 7, 5);
INSERT INTO exams (discipline_code, group_code, student_id, grade) VALUES (2, 2, 7, 5);
INSERT INTO exams (discipline_code, group_code, student_id, grade) VALUES (1, 2, 8, 5);
INSERT INTO exams (discipline_code, group_code, student_id, grade) VALUES (2, 2, 8, 5);
INSERT INTO exams (discipline_code, group_code, student_id, grade) VALUES (1, 2, 9, 5);
INSERT INTO exams (discipline_code, group_code, student_id, grade) VALUES (2, 2, 9, 5);
INSERT INTO exams (discipline_code, group_code, student_id, grade) VALUES (1, 2, 10, 5);
INSERT INTO exams (discipline_code, group_code, student_id, grade) VALUES (2, 2, 10, 5);
INSERT INTO exams (discipline_code, group_code, student_id, grade) VALUES (1, 2, 11, 5);
INSERT INTO exams (discipline_code, group_code, student_id, grade) VALUES (2, 2, 11, 5);
INSERT INTO exams (discipline_code, group_code, student_id, grade) VALUES (1, 2, 12, 5);
INSERT INTO exams (discipline_code, group_code, student_id, grade) VALUES (2, 2, 12, 5);
INSERT INTO exams (discipline_code, group_code, student_id, grade) VALUES (1, 2, 13, 5);
INSERT INTO exams (discipline_code, group_code, student_id, grade) VALUES (2, 2, 13, 5);
INSERT INTO exams (discipline_code, group_code, student_id, grade) VALUES (1, 2, 14, 5);
INSERT INTO exams (discipline_code, group_code, student_id, grade) VALUES (2, 2, 14, 5);
INSERT INTO exams (discipline_code, group_code, student_id, grade) VALUES (1, 2, 15, 5);
INSERT INTO exams (discipline_code, group_code, student_id, grade) VALUES (2, 2, 15, 5);
INSERT INTO exams (discipline_code, group_code, student_id, grade) VALUES (1, 2, 16, 5);
INSERT INTO exams (discipline_code, group_code, student_id, grade) VALUES (2, 2, 16, 5);
INSERT INTO exams (discipline_code, group_code, student_id, grade) VALUES (1, 2, 17, 5);
INSERT INTO exams (discipline_code, group_code, student_id, grade) VALUES (2, 2, 17, 5);
INSERT INTO exams (discipline_code, group_code, student_id, grade) VALUES (1, 2, 18, 5);
INSERT INTO exams (discipline_code, group_code, student_id, grade) VALUES (2, 2, 18, 5);
INSERT INTO exams (discipline_code, group_code, student_id, grade) VALUES (1, 2, 19, 5);
INSERT INTO exams (discipline_code, group_code, student_id, grade) VALUES (2, 2, 19, 5);
INSERT INTO exams (discipline_code, group_code, student_id, grade) VALUES (1, 2, 20, 5);
INSERT INTO exams (discipline_code, group_code, student_id, grade) VALUES (2, 2, 20, 5);
INSERT INTO exams (discipline_code, group_code, student_id, grade) VALUES (1, 2, 21, 5);
INSERT INTO exams (discipline_code, group_code, student_id, grade) VALUES (2, 2, 21, 5);
INSERT INTO exams (discipline_code, group_code, student_id, grade) VALUES (1, 2, 22, 5);
INSERT INTO exams (discipline_code, group_code, student_id, grade) VALUES (2, 2, 22, 5);
INSERT INTO exams (discipline_code, group_code, student_id, grade) VALUES (1, 2, 23, 5);
INSERT INTO exams (discipline_code, group_code, student_id, grade) VALUES (2, 2, 23, 5);
INSERT INTO exams (discipline_code, group_code, student_id, grade) VALUES (1, 2, 24, 5);
INSERT INTO exams (discipline_code, group_code, student_id, grade) VALUES (2, 2, 24, 5);
INSERT INTO exams (discipline_code, group_code, student_id, grade) VALUES (1, 2, 25, 5);
INSERT INTO exams (discipline_code, group_code, student_id, grade) VALUES (2, 2, 25, 5);
INSERT INTO exams (discipline_code, group_code, student_id, grade) VALUES (1, 2, 26, 5);
INSERT INTO exams (discipline_code, group_code, student_id, grade) VALUES (2, 2, 26, 5);
INSERT INTO exams (discipline_code, group_code, student_id, grade) VALUES (1, 2, 27, 5);
INSERT INTO exams (discipline_code, group_code, student_id, grade) VALUES (2, 2, 27, 5);
INSERT INTO exams (discipline_code, group_code, student_id, grade) VALUES (1, 2, 28, 5);
INSERT INTO exams (discipline_code, group_code, student_id, grade) VALUES (2, 2, 28, 5);
INSERT INTO exams (discipline_code, group_code, student_id, grade) VALUES (1, 2, 29, 5);
INSERT INTO exams (discipline_code, group_code, student_id, grade) VALUES (2, 2, 29, 5);
INSERT INTO exams (discipline_code, group_code, student_id, grade) VALUES (1, 2, 30, 5);
INSERT INTO exams (discipline_code, group_code, student_id, grade) VALUES (2, 2, 30, 5);
INSERT INTO exams (discipline_code, group_code, student_id, grade) VALUES (1, 2, 31, 5);
INSERT INTO exams (discipline_code, group_code, student_id, grade) VALUES (2, 2, 31, 5);
INSERT INTO exams (discipline_code, group_code, student_id, grade) VALUES (1, 2, 32, 5);
INSERT INTO exams (discipline_code, group_code, student_id, grade) VALUES (2, 2, 32, 5);